import { createProject } from '../types/project';

export const getMockProjects = () => [
  createProject({
    id: 'AC-1234',
    name: '에어컨 프로젝트',
    description: '신규 냉매를 적용한 에어컨 개발 프로젝트',
    stage1: {
      productGroup: 'AC시리즈',
      manufacturer: 'LG전자',
      vendor: '삼성전자',
      productTool: 'AC-Tool-2024',
      derivativeModel: 'AC-PRO-V2',
      launchDate: '2024-12-01',
      launchDateExecuted: false,
      researcher1: '김기구',
      researcher2: '이회로',
      massProductionDate: '2024-11-15',
      massProductionDateExecuted: false,
      notes: '신규 냉매 적용'
    },
    stage2: {
      pilotProductionDate: '2024-10-01',
      pilotProductionDateExecuted: true,
      pilotQuantity: '10',
      pilotReceiveDate: '2024-10-05',
      pilotReceiveDateExecuted: true,
      techTransferDate: '2024-10-10',
      techTransferDateExecuted: false,
      installationEntity: '기술팀',
      serviceEntity: 'A/S팀',
      trainingDate: '2024-10-15',
      trainingDateExecuted: false,
      orderAcceptanceDate: '2024-10-20',
      orderAcceptanceDateExecuted: false,
      trainingCompleted: false,
      manualUploaded: true,
      techGuideUploaded: false,
      notes: '기술 이전 완료'
    },
    stage3: {
      initialProductionDate: '2024-11-01',
      initialProductionDateExecuted: false,
      firstOrderDate: '2024-11-10',
      firstOrderDateExecuted: false,
      bomManager: '박부품',
      bomTargetDate: '2024-10-25',
      bomTargetDateExecuted: false,
      priceManager: '정단가',
      priceTargetDate: '2024-10-30',
      priceTargetDateExecuted: false,
      partsDeliveryDate: '2024-11-05',
      partsDeliveryDateExecuted: false,
      partsReceived: true,
      branchOrderEnabled: false,
      issueResolved: true,
      notes: '부품 조달 지연 해결'
    }
  }),
  createProject({
    id: 'WT-5678',
    name: '정수기 프로젝트',
    description: '직수형 정수기 개발 프로젝트',
    stage1: {
      productGroup: '정수기시리즈',
      manufacturer: 'SK매직',
      vendor: 'LG전자',
      productTool: 'WT-Tool-2024',
      derivativeModel: 'WT-PREMIUM-V3',
      launchDate: '2025-01-15',
      launchDateExecuted: false,
      researcher1: '최기구',
      researcher2: '한회로',
      massProductionDate: '2025-01-01',
      massProductionDateExecuted: false,
      notes: '직수형 정수기'
    },
    stage2: {
      pilotProductionDate: '2024-11-15',
      pilotProductionDateExecuted: false,
      pilotQuantity: '15',
      pilotReceiveDate: '2024-11-20',
      pilotReceiveDateExecuted: false,
      techTransferDate: '2024-11-25',
      techTransferDateExecuted: false,
      installationEntity: '설치팀',
      serviceEntity: '정수팀',
      trainingDate: '2024-12-01',
      trainingDateExecuted: false,
      orderAcceptanceDate: '2024-12-05',
      orderAcceptanceDateExecuted: false,
      trainingCompleted: false,
      manualUploaded: false,
      techGuideUploaded: false,
      notes: '필터 기술 검토 중'
    },
    stage3: {
      initialProductionDate: '',
      initialProductionDateExecuted: false,
      firstOrderDate: '',
      firstOrderDateExecuted: false,
      bomManager: '',
      bomTargetDate: '',
      bomTargetDateExecuted: false,
      priceManager: '',
      priceTargetDate: '',
      priceTargetDateExecuted: false,
      partsDeliveryDate: '',
      partsDeliveryDateExecuted: false,
      partsReceived: false,
      branchOrderEnabled: false,
      issueResolved: false,
      notes: ''
    }
  }),
  createProject({
    id: 'TV-9012',
    name: 'OLED TV 프로젝트',
    description: '차세대 OLED 디스플레이 기술 적용',
    stage1: {
      productGroup: 'TV시리즈',
      manufacturer: 'Samsung',
      vendor: 'LG디스플레이',
      productTool: 'TV-Tool-2024',
      derivativeModel: 'OLED-ULTRA-V1',
      launchDate: '2024-09-30',
      launchDateExecuted: true,
      researcher1: '김디스',
      researcher2: '박플레이',
      massProductionDate: '2024-09-15',
      massProductionDateExecuted: true,
      notes: 'HDR 기술 적용 완료'
    },
    stage2: {
      pilotProductionDate: '2024-08-01',
      pilotProductionDateExecuted: true,
      pilotQuantity: '50',
      pilotReceiveDate: '2024-08-05',
      pilotReceiveDateExecuted: true,
      techTransferDate: '2024-08-10',
      techTransferDateExecuted: true,
      installationEntity: '디스플레이팀',
      serviceEntity: 'TV서비스팀',
      trainingDate: '2024-08-15',
      trainingDateExecuted: true,
      orderAcceptanceDate: '2024-08-20',
      orderAcceptanceDateExecuted: true,
      trainingCompleted: true,
      manualUploaded: true,
      techGuideUploaded: true,
      notes: '모든 단계 완료'
    },
    stage3: {
      initialProductionDate: '2024-09-01',
      initialProductionDateExecuted: true,
      firstOrderDate: '2024-09-05',
      firstOrderDateExecuted: true,
      bomManager: '이부품',
      bomTargetDate: '2024-08-25',
      bomTargetDateExecuted: true,
      priceManager: '최단가',
      priceTargetDate: '2024-08-30',
      priceTargetDateExecuted: true,
      partsDeliveryDate: '2024-09-03',
      partsDeliveryDateExecuted: true,
      partsReceived: true,
      branchOrderEnabled: true,
      issueResolved: true,
      notes: '성공적 출시 완료'
    }
  })
];