import { createProject } from '../types/project';

export const getMockProjects = () => [
  createProject({
    id: 'AC-1234',
    name: '에어컨 프로젝트',
    description: '신규 냉매를 적용한 에어컨 개발 프로젝트',
    stage1: {
      productGroup: 'AC시리즈',
      manufacturer: 'LG전자',
      vendor: '삼성전자',
      derivativeModel: 'AC-PRO-V2, AC-PRO-V2W',
      launchDate: '2024-12-01',
      productManager: '김상품',
      mechanicalEngineer: '김기구',
      circuitEngineer: '이회로',
      massProductionDate: '2024-11-15',
      launchDateExecuted: false,
      massProductionDateExecuted: false,
      notes: ''
    },
    stage2: {
      pilotProductionDate: '2024-10-01',
      techTransferDate: '2024-10-10',
      installationParty: '기술팀',
      serviceParty: 'A/S팀',
      trainingDate: '2024-10-15',
      userManualUpload: 'AC_사용자설명서_v1.pdf',
      techManualUpload: 'AC_기술교본_v1.pdf',
      pilotProductionDateExecuted: true,
      techTransferDateExecuted: false,
      trainingDateExecuted: false,
      userManualUploaded: true,
      techManualUploaded: false,
      notes: ''
    },
    stage3: {
      firstPartsOrderDate: '2024-11-10',
      bomManager: '박부품',
      bomCompletionDate: '2024-10-25',
      priceManager: '정단가',
      priceRegistrationDate: '2024-10-30',
      partsReceiptDate: '2024-11-05',
      partsReceiptManager: '최입고',
      branchOrderGuideDate: '2024-11-12',
      firstPartsOrderDateExecuted: false,
      bomCompletionDateExecuted: false,
      priceRegistrationDateExecuted: false,
      partsReceiptDateExecuted: false,
      branchOrderGuideDateExecuted: false,
      notes: ''
    }
  }),
  createProject({
    id: 'WT-5678',
    name: '정수기 프로젝트',
    description: '직수형 정수기 개발 프로젝트',
    stage1: {
      productGroup: '정수기시리즈',
      manufacturer: 'SK매직',
      vendor: 'LG전자',
      derivativeModel: 'WT-PREMIUM-V3, WT-PREMIUM-V3B',
      launchDate: '2025-01-15',
      productManager: '이상품',
      mechanicalEngineer: '최기구',
      circuitEngineer: '한회로',
      massProductionDate: '2025-01-01',
      launchDateExecuted: false,
      massProductionDateExecuted: false,
      notes: ''
    },
    stage2: {
      pilotProductionDate: '2024-11-15',
      techTransferDate: '2024-11-25',
      installationParty: '설치팀',
      serviceParty: '정수팀',
      trainingDate: '2024-12-01',
      userManualUpload: '',
      techManualUpload: '',
      pilotProductionDateExecuted: false,
      techTransferDateExecuted: false,
      trainingDateExecuted: false,
      userManualUploaded: false,
      techManualUploaded: false,
      notes: ''
    },
    stage3: {
      firstPartsOrderDate: '',
      bomManager: '',
      bomCompletionDate: '',
      priceManager: '',
      priceRegistrationDate: '',
      partsReceiptDate: '',
      partsReceiptManager: '',
      branchOrderGuideDate: '',
      firstPartsOrderDateExecuted: false,
      bomCompletionDateExecuted: false,
      priceRegistrationDateExecuted: false,
      partsReceiptDateExecuted: false,
      branchOrderGuideDateExecuted: false,
      notes: ''
    }
  }),
  createProject({
    id: 'TV-9012',
    name: 'OLED TV 프로젝트',
    description: '차세대 OLED 디스플레이 기술 적용',
    stage1: {
      productGroup: 'TV시리즈',
      manufacturer: 'Samsung',
      vendor: 'LG디스플레이',
      derivativeModel: 'OLED-ULTRA-V1, OLED-ULTRA-V1S',
      launchDate: '2024-09-30',
      productManager: '박상품',
      mechanicalEngineer: '김디스',
      circuitEngineer: '박플레이',
      massProductionDate: '2024-09-15',
      launchDateExecuted: true,
      massProductionDateExecuted: true,
      notes: ''
    },
    stage2: {
      pilotProductionDate: '2024-08-01',
      techTransferDate: '2024-08-10',
      installationParty: '디스플레이팀',
      serviceParty: 'TV서비스팀',
      trainingDate: '2024-08-15',
      userManualUpload: 'OLED_TV_사용자설명서_v1.pdf',
      techManualUpload: 'OLED_TV_기술교본_v1.pdf',
      pilotProductionDateExecuted: true,
      techTransferDateExecuted: true,
      trainingDateExecuted: true,
      userManualUploaded: true,
      techManualUploaded: true,
      notes: ''
    },
    stage3: {
      firstPartsOrderDate: '2024-09-05',
      bomManager: '이부품',
      bomCompletionDate: '2024-08-25',
      priceManager: '최단가',
      priceRegistrationDate: '2024-08-30',
      partsReceiptDate: '2024-09-03',
      partsReceiptManager: '김입고',
      branchOrderGuideDate: '2024-09-08',
      firstPartsOrderDateExecuted: true,
      bomCompletionDateExecuted: true,
      priceRegistrationDateExecuted: true,
      partsReceiptDateExecuted: true,
      branchOrderGuideDateExecuted: true,
      notes: ''
    }
  })
];